# -*- coding: utf-8 -*-
"""week 4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YPseR73rOjrh0opOwzzykTrMzu86Clyk
"""

import pandas as pd
import matplotlib.pyplot as plt

import numpy as np

"""한글 설정"""

!sudo apt-get install -y fonts-nanum
!sudo fc-cache -fv
!rm ~/.cache/matplotlib -rf

plt.rc('font', family='NanumBarunGothic')

df_temp = pd.read_csv('/content/seoul_temp.csv')
df_temp

"""상위 5개"""

df_temp.head(5)

"""하위 5개"""

df_temp.tail(5)

"""인포"""

df_temp.info()

"""컬럼별 통계량"""

df_temp.describe()

"""행열의 크기"""

df_temp.shape

"""컬럼이름 확인"""

df_temp.columns

"""인덱스 변경"""

df_temp.set_index('연도',inplace=True)
df_temp

"""선그래프 그리기"""

plt.plot(df_temp.index,df_temp['평균기온'])
plt.show()

"""최고기온"""

plt.plot(df_temp.index,df_temp['최고기온'])
plt.show()

"""최저기온"""

plt.plot(df_temp.index,df_temp['최저기온'])
plt.show()

"""그래프 제목 표시"""

plt.plot(df_temp.index ,df_temp['평균기온'])
plt.title('avg temp')
plt.show()
plt.plot(df_temp.index,df_temp['최고기온'])
plt.title('max temp')
plt.show()

"""서울시 연간 기온 미션"""

plt.plot(df_temp.index,df_temp['평균기온'])
plt.plot(df_temp.index,df_temp['최고기온'])
plt.plot(df_temp.index,df_temp['최저기온'])
plt.title('서울시연간기온')
plt.show()

"""x좌표 y좌표 설정"""

plt.plot(df_temp.index,df_temp['평균기온'])
plt.plot(df_temp.index,df_temp['최고기온'])
plt.plot(df_temp.index,df_temp['최저기온'])
plt.title('서울시연간기온')
plt.xlabel('연도')
plt.ylabel('기온')
plt.show()

"""차트 색 바꾸기"""

plt.plot(df_temp.index,df_temp['평균기온'])
plt.plot(df_temp.index,df_temp['최고기온'])
plt.plot(df_temp.index,df_temp['최저기온'])
plt.title('서울시연간기온')
plt.xlabel('연도')
plt.ylabel('기온')
plt.plot(x,y,color='red')
plt.grid()
plt.show()

"""마커 넣기"""

plt.plot(df_temp.index,df_temp['평균기온'])
plt.plot(df_temp.index,df_temp['최고기온'])
plt.plot(df_temp.index,df_temp['최저기온'])
plt.title('서울시연간기온')
plt.xlabel('연도')
plt.ylabel('기온')
plt.plot(df_temp.index,df_temp['평균기온'],marker='o')
plt.show()

"""차트 크기 정하기"""

plt.figure(figsize=(20,10))
plt.plot(df_temp.index,df_temp['평균기온'])
plt.plot(df_temp.index,df_temp['최고기온'])
plt.plot(df_temp.index,df_temp['최저기온'])
plt.title('서울시연간기온')
plt.xlabel('연도')
plt.ylabel('기온')
plt.plot(df_temp.index,df_temp['평균기온'],marker='o')
plt.plot(df_temp.index,df_temp['최고기온'],marker='o')
plt.plot(df_temp.index,df_temp['최저기온'],marker='o')
plt.show()

"""1행 2열 그래프 그리기"""

fig,ax = plt.subplots(nrows = 2, ncols = 3, figsize = (6,6))

"""정비례 그래프"""

ax[0,1].plot(np.arange(1,11,1))
fig

"""반비례"""

ax[1,2].plot(np.arange(11,1,-1))
fig

"""산점도"""

x1=np.random.rand(50)
y1=np.random.rand(50)

ax[0,0].scatter(x1,y1)
fig

"""파이차트"""

label = ['A','B','AB','O']
size = [34.8,32.9,14.7,17.6]


ax[0,2]=plt.pie(size,labels=label,autopct='%.1f%%')


label = ['A','B','C','D']
size = [40.0,10.0,20.0,30.0]


ax[1,0]=plt.pie(size,labels=label,autopct='%.1f%%')
fig

"""케익 선호도"""

label = ['초코','생크림','치즈','딸기']
size = [40.0,10.0,20.0,30.0]


ax[0,2]=plt.pie(size,labels=label,autopct='%.1f%%')
fig

label = ['초코','생크림','치즈','딸기']
size = [40.0,10.0,20.0,30.0]


# ax[0,2]=plt.pie(size,labels=label,autopct='%.1f%%')

ax[1,0].pie(size,labels=label,autopct='%.1f%%')

fig

막대

ax[1,1].bar(df_temp.index,df_temp['평균기온'])
fig